# Generated by Django 4.1.4 on 2023-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_basket_created_at_basket_product_basket_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
